### ISSUE TITLE
Not receiving activesupport notifications under 1.3.1

### ISSUE THREAD

**Issue by iftheshoefritz** [flippercloud/flipper#886]
We upgraded from 1.1.2 to 1.3.1 and found that we no longer get activesupport notifications with this line in an initializer:

```
ActiveSupport::Notifications.subscribe("feature_operation.flipper") do
   # block was being called in 1.1.2 but not in 1.3.1
end
```

What might have changed?

**Comment by thomas-tz** [comment]
It's probably because of `test_help.rb` in https://github.com/flippercloud/flipper/blob/main/lib/flipper/test_help.rb. It doesn't pass any options for the instrumenter (usually active support notifications by default if you're using rails) and it defaults to a "noop" instrumenter, which I believe doesn't do anything?

It would be nice if it was possible to have it respect the instrumenter in the test help
