### ISSUE TITLE
Use Lograge for flipper logs

### ISSUE THREAD

**Issue by devth** [flippercloud/flipper#891]
I have my rails logger configured with [lograge](https://github.com/roidrage/lograge) JSON output which plays nicely with Datadog. However, my flipper logs are still showing up in the default format, e,g.:

```shell
[1m[36mFlipper feature(my_flag) enabled? true (0.0ms)[0m  [ actors=[#<Flipper::Types::Actor:0x01107f8711517018 @actor=#<MyValidation::Foo:0x00107187111f3110 @email="foo@bar.com">, @value="foo@bar.com">] gate_name=boolean ]
```

While all my controller logs show up nicely in JSON. I tried configuring flipper to use the Rails logger in `config/production.rb`:

```ruby
  # Use the rails logger in flipper
  config.flipper.logger = Rails.logger
```

**Comment by jnunemaker** [comment]
I think you'll need to turn logging off ([source](https://github.com/flippercloud/flipper/blob/4b911dd3d185b5ba8d7f0be1323a5ba633565af1/lib/flipper/engine.rb#L61-L67)). You can do this in config/application.rb:

```ruby
config.flipper.log = false
```

Then, you'll need a new log subscriber like our [default one](https://github.com/flippercloud/flipper/blob/main/lib/flipper/instrumentation/log_subscriber.rb) (just copy and tweak it to output json instead of default stuff).

If you wanted to make a json one I'd be happy to merge it in flipper proper. Once that is done, you'll just need to attach it like we do ([here](https://github.com/flippercloud/flipper/blob/4b911dd3d185b5ba8d7f0be1323a5ba633565af1/lib/flipper/instrumentation/log_subscriber.rb#L100) and [here](https://github.com/flippercloud/flipper/blob/4b911dd3d185b5ba8d7f0be1323a5ba633565af1/lib/flipper/instrumentation/log_subscriber.rb#L75-L77)) with the default one.

**Comment by devth** [comment]
Thanks @jnunemaker! I'll try this out.
